-- ============================================================
-- Capital Finplus Academy — seed sample data (pre-Supabase defaults)
-- Safe to run once on an empty database. Re-running will duplicate rows
-- (courses/articles/etc have no unique constraint on title), so only
-- run this if these tables are currently empty.
-- ============================================================

-- site_content
insert into public.site_content (key, value) values ('hero', '{"line1":"Master","accent":"Markets.","line3":"Build Real Wealth.","sub":"YOUR TRADING JOURNEY STARTS HERE.<br>No question is too basic. No doubt is too small. <span class=\"hero-ask-us\">Ask us.</span>","badge":"Trusted by 500+ Traders","cta1":"Book a Discovery Call","cta2":"Explore Your Path"}'::jsonb) on conflict (key) do update set value = excluded.value;
insert into public.site_content (key, value) values ('about', '{"heading":"Building Traders Through<br>Process, Discipline<br>And Market Understanding","p1":"With over 15 years of experience in target-based investing in equity markets, the founder has developed a disciplined approach to identifying investment opportunities with managed risk. Over the years, he expanded his expertise into mid-term and short-term trading strategies, with a strong focus on market structure, risk management, and consistency across equity and commodity markets.","p2":"He holds a Bachelor''s degree in Engineering and a Master''s degree in Business Administration (MBA). Having worked with leading multinational organizations such as Cisco and Siemens during the early part of his professional career, he developed a deep appreciation for structured processes, analytical thinking, and disciplined execution — principles that continue to guide his approach to trading and investing.","p3":"","founderName":"Pravesh Kumar","founderTitle":"Founder & Head Mentor — CFA","bio":"\"Driven by a passion for simplifying market concepts and helping traders avoid common pitfalls, I founded CFA Academy — the educational arm of Capital Finplus Advizors. Through practical, experience-driven mentorship, the academy focuses on helping traders understand the why behind every decision, rather than blindly following indicators, tips, or market noise. The goal is simple: help traders and investors develop sustainable habits, independent thinking, and the confidence to navigate markets with consistency.\"","credentials":["CFA Academy","15+ Years Markets","Equity Research","500+ Students"],"founderPhoto":"assets/founder.jpg"}'::jsonb) on conflict (key) do update set value = excluded.value;
insert into public.site_content (key, value) values ('stats', '{"students":"500","experience":"15","rating":"4.8"}'::jsonb) on conflict (key) do update set value = excluded.value;
insert into public.site_content (key, value) values ('contact', '{"email":"connect@capitalfinplusadvizors.com","whatsapp":"+91 93503 31521","telegram":"@capitalfinplusadvizors","telegramUrl":"https://t.me/capitalfinplusadvizors","instagram":"@capital_finplus_academy","instagramUrl":"https://www.instagram.com/capital_finplus_academy?utm_source=qr","youtube":"@capitalfinplusadvizors","youtubeUrl":"https://youtube.com/@capitalfinplusadvizors?si=Yo1yx_mgLksfNjYD","twitter":"@capitalfinplus_in","twitterUrl":"","calendlyUrl":"https://calendly.com/connect-capitalfinplusadvizors/discovery-call-30-mins","razorpayKeyId":""}'::jsonb) on conflict (key) do update set value = excluded.value;
insert into public.site_content (key, value) values ('legal', '{"disclaimer":"Capital Finplus Academy is an educational platform. Trading in securities involves risk of loss. All course content is for educational purposes only and does not constitute investment advice. Please consult a SEBI-registered advisor before making investment decisions. Past performance is not indicative of future results."}'::jsonb) on conflict (key) do update set value = excluded.value;

-- courses
insert into public.courses (name, subtitle, "desc", level, group_name, features, features_rich, price, price_sub, cta_label, cta_link, is_modal, sort_order) values ('Essentials', 'The CFA System — Foundation', 'Build the right foundation before your first trade. Understand what drives price movement, why trends form, and how the CFA Trading Framework sets you up for success.', 'Free · Beginner', 'CFA Intraday Trading', '["What drives price movement","Market structure & price behaviour","The right trading mindset","Traps, fakeouts & how to avoid them","CFA Trading Framework — Introduction"]'::jsonb, '', 'FREE', 'No credit card needed', 'Get Started Free', 'javascript:void(0)', true, 0);
insert into public.courses (name, subtitle, "desc", level, group_name, features, features_rich, price, price_sub, cta_label, cta_link, is_modal, sort_order) values ('Edge + Precision', 'Two Modules — One Complete Framework', 'Master the complete CFA Trading Framework across two power-packed modules. Develop a structured, repeatable trading process and learn to execute with precision.', 'Intermediate · Bundle', 'CFA Intraday Trading', '["Complete CFA Trading System","Chart setup & workspace configuration","Entry, Target & Stop Loss methodology","Detailed backtesting & validation","Option premium charts mastery","Strike price selection & position sizing"]'::jsonb, '## EDGE
Develop a Structured & Repeatable Trading Process
Learn the complete CFA Trading System and the logic behind every trade.
- The complete CFA Trading System
- Why the system works across different market conditions
- Chart setup and workspace configuration
- Tools to identify Market Structure and trend identification
- Timeframe selection and alignment
- Entry, Target and Stop Loss methodology
- Detailed backtesting
- Building confidence through data-driven validation
> Outcome: Develop a repeatable framework that helps identify high-probability trading opportunities with predefined risk. EDGE and PRECISION includes live market support as and when setup is formed.

## PRECISION
Master Option Buying and Selling Through Premium Charts
Move beyond index charts and learn to trade the instrument that actually determines your profit and loss.
- Understanding option premium behaviour
- Why option premium charts matter more for option buyers
- How to select the right strike price
- Understanding option writers'' perspective
- Identifying high-probability entry zones on premium charts
- Timing option buying with market structure
- Position sizing and trade execution
- Building trading discipline and psychology
- Developing consistency in real market conditions
> Outcome: Learn to execute trades with greater precision, better timing, and improved risk management using option premium charts.', '₹5,999', '+ GST · One-time', 'Enroll Now', 'payment.html?course=2', false, 1);
insert into public.courses (name, subtitle, "desc", level, group_name, features, features_rich, price, price_sub, cta_label, cta_link, is_modal, sort_order) values ('The CFA Academy Framework for Stock Investing', 'Target-Based Investing Masterclass', 'A complete investing framework covering market structure, sector rotation, stock selection, portfolio construction, and investor psychology for sustainable wealth creation.', 'Advanced', null, '["Market structure & sector rotation","Stock selection & screening framework","Portfolio construction strategy","Investor psychology & discipline","Capstone project — Build your own framework"]'::jsonb, '', '₹4,999', '+ GST · One-time', 'Enroll Now', 'payment.html?course=3', false, 2);

-- testimonials
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Kavya S.', 'CA Professional, Mumbai · Equity + Options', 5, 'I''d tried 4 other courses before Capital Finplus Academy. This is the first one that felt like being mentored by someone who actually trades. The live sessions changed everything.', 0, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Arjun P.', 'Business Owner, Hyderabad · Swing Trading', 5, 'The free discovery call gave me more clarity than 6 months of self-study. Booked the course the next day. My swing trades have been far more consistent since.', 1, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Priya T.', 'HR Manager, Pune · Equity Markets', 5, 'As a complete beginner I was intimidated. But the curriculum is so well structured — from zero to placing my first live F&O trade in 8 weeks with real confidence.', 2, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Vikas R.', 'IT Consultant, Chennai · Crypto + Equity', 5, 'The Telegram group and weekly reviews kept me accountable. I''ve been in markets 3 years but this is the first time I felt like I had a proper system, not just guesses.', 3, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Siddharth N.', 'Doctor, Delhi NCR · Part-time Trader', 5, 'The 1-on-1 call after I completed the course helped me build a watchlist strategy specific to my schedule. That personalised attention is what sets Capital Finplus apart.', 4, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Aditya R.', 'Marketing Manager, Mumbai · Discovery Call', 5, 'I already had my own trading strategy before the free discovery call. <span class="blur-name">Pravesh Sir</span> identified that my risk-reward management needed improvement and suggested a simple way to optimize my stop loss while keeping my targets. The biggest difference has been my ability to hold trades with conviction instead of exiting prematurely. Sometimes it''s not about finding a new strategy — it''s about refining the one you already have.', 5, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Neha K.', 'Pharmacist, Ahmedabad · Discovery Call', 5, 'I got my strategy reviewed on the free discovery call and realized it could capture points on the index but was not ideal for option buying since it ignored theta decay and premium behaviour. The team introduced me to the CFA trading framework, which aligns far better with market structure for option buyers. I now approach trades with much greater clarity and confidence.', 6, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Rohit D.', 'Bank Employee, Pune · Live Intraday Sessions', 5, 'The biggest lesson I learned was that not every market move is meant to be traded. The CFA framework taught me to focus only on my setups. Once I stopped chasing trades and started waiting, my decision-making improved dramatically.', 7, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Arun Thakker', 'Operations Manager, Gurugram · 1-on-1 Mentorship', 5, 'Before the mentorship I was constantly switching indicators and strategies. The CFA system showed me how to build a structured trading plan and follow it consistently. Understanding Higher Highs, Higher Lows, and market structure simplified trading far more than any indicator ever did.', 8, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Meera J.', 'Architect, Jaipur · 1-on-1 Mentorship', 5, 'Started with a discovery call and then opted for mentorship — it was truly one-on-one, all my doubts clarified. Recorded courses can explain setups, but they don''t teach you what to think when the market is moving in real time. Learning the right way to think took almost 3 months, and now I wait for the setup and execute with clarity.', 9, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Karan B.', 'Sales Executive, Indore · 1-on-1 Mentorship', 5, 'Recorded courses had not helped me much earlier — they only provide setups, which are not enough. Having a mentor helped me emphasise patience. The mentorship taught me that waiting for the right setup is often more profitable than taking multiple random trades. Learning to stay away from noise and clutter was a game-changer.', 10, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Tanvi S.', 'Graphic Designer, Surat · Live Intraday Sessions', 4, 'The CFA framework helped me understand traps and fakeouts that used to catch me regularly. Instead of reacting to every candle, I learned to focus on structure, confirmations, and probabilities. That shift alone improved my confidence as a trader.', 11, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Abhishek P.', 'Civil Engineer, Nagpur · 1-on-1 Mentorship', 4, 'One of the most underrated aspects of the mentorship is the focus on psychology. Seeing similar setups unfold day after day teaches you to trust the process. Over time, it becomes easier to execute without fear, greed, or FOMO.', 12, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Divya M.', 'Chartered Accountant, Mumbai · CFA Investment System', 5, 'The CFA Investing Course significantly improved my approach to long-term investing. One of the biggest takeaways was learning how to find the right entry points to build positions with confidence in bluechip companies. The concepts around market cycles and sector rotation helped me understand where institutional money is flowing and select stocks more strategically.', 13, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Yash K.', 'Data Analyst, Bangalore · Live Intraday Sessions', 4, 'I am very satisfied with the CFA trading framework and how the setup was explained during the live sessions — practical and easy to understand. One suggestion: a more extensive backtesting review covering at least six months of historical data would further strengthen confidence in the setup across different market conditions.', 14, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Pooja N.', 'School Teacher, Lucknow · 1-on-1 Mentorship', 4, 'I used to overtrade because I felt I needed to be in the market all the time. Through mentorship I learned that sometimes the best trade is no trade. Having someone guide you through live market conditions helps develop discipline that is difficult to build alone.', 15, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Imran S.', 'Logistics Manager, Hyderabad · Live Intraday Sessions', 4, 'The emphasis on risk-reward completely changed how I approach trading. Earlier I focused only on whether a trade would work. Now I evaluate every opportunity based on risk, reward, and market structure. This simple change brought much-needed consistency to my process.', 16, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Ritika V.', 'Interior Designer, Chandigarh · 1-on-1 Mentorship', 5, 'The beauty of the CFA setup lies in its simplicity. Everything starts with market structure and a clear plan. Once the setup forms, the focus shifts to execution rather than prediction. That structured approach removes much of the stress associated with trading.', 17, true);
insert into public.testimonials (name, role, rating, quote, sort_order, is_published) values ('Gaurav T.', 'Software Developer, Noida · 1-on-1 Mentorship', 5, 'What sets the mentorship apart is learning how to think, not what to think. The discussions around live market scenarios, trade management, patience, and execution helped me develop a trader''s mindset. The course provides the framework, but the mentorship helps you apply it consistently in real market conditions.', 18, true);

-- articles
insert into public.articles (title, excerpt, body, category, cat, access, date, icon, color, bg, featured, readtime) values ('Understanding Market Structure: Why Price Moves the Way It Does', 'Before you place a single trade, you need to understand the foundation — how price creates structure, why breakouts happen, and what smart money is doing.', '
      <p>Before you place a single trade, you need to understand the single most important question in technical analysis: <strong>why does price move the way it does?</strong> Most retail traders skip straight to indicators and patterns without ever answering this — and it shows in their results.</p>
      <h3>What is Market Structure?</h3>
      <p>Market structure is the sequence of highs and lows that price creates as it moves. An uptrend is a series of higher highs and higher lows. A downtrend is a series of lower highs and lower lows. A ranging market creates roughly equal highs and equal lows. Simple to say — but most traders never actually internalise this before they start trading real money.</p>
      <p>Every chart, on every timeframe, is telling you a structural story. Your first job before any indicator, any news headline, any "tip" from a WhatsApp group, is to read that story honestly.</p>
      <h3>Why Breakouts Happen Where They Do</h3>
      <p>Price gravitates toward areas of liquidity — zones where large amounts of buy or sell orders cluster, usually just beyond an obvious swing high or swing low. This is exactly why breakouts so often happen at those levels. Market makers and institutional desks need to fill very large orders, and the cleanest way to do that is to trigger the stop-losses sitting just past the "obvious" level, generating the liquidity they need to fill their own size.</p>
      <div class="highlight-box">If a level looks "too obvious" to you as a retail trader, it looks exactly as obvious to the algorithms and institutional desks on the other side of your trade — which is precisely why it gets hunted before the real move begins.</div>
      <h3>What Smart Money Is Actually Doing</h3>
      <p>Institutional traders don''t chase price. They plan positions around supply and demand zones, then wait patiently for price to come to them. The retail habit of buying breakouts at market price is exactly the liquidity event that institutions rely on to fill their own positions at scale — which is why so many breakout entries immediately reverse.</p>
      <h3>The CFA Framework Application</h3>
      <p>In the CFA Trading System, every trade starts with a market structure assessment — before we ever look at an entry trigger. We map the current structural bias, identify the last significant swing high/low, and confirm we are trading in the direction of the dominant structure (or have a very specific, well-defined reason for fading it). This single habit eliminates the majority of low-quality setups before they ever cost you money.</p>
      <p style="color:rgba(255,224,102,0.9);font-style:italic;margin-top:1.5rem;">Want to go deeper? This concept is a cornerstone of our Intraday Trading Essentials course — available free. Book a Discovery Call to start.</p>
    ', 'Technical Analysis', 'technical-analysis', 'free', '2026-06-04', 'candlestick_chart', '#F4C20D', 'linear-gradient(135deg,#2a2008 0%,#4a3508 100%)', false, '8 min read');
insert into public.articles (title, excerpt, body, category, cat, access, date, icon, color, bg, featured, readtime) values ('The 2% Rule and Why Most Traders Ignore It (Until They Blow Their Account)', 'Position sizing is the unsexy secret behind consistent profitability. One bad day should never wipe out a great month.', '
      <p>Ask any consistently profitable trader what the single most important rule in their playbook is, and almost all of them will say some version of: <strong>never risk more than 2% of your capital on any single trade.</strong> It isn''t glamorous advice. It also happens to be the difference between traders who are still in the game five years from now and those who aren''t.</p>
      <h3>Why 2%?</h3>
      <p>The 2% rule is mathematically protective. If you lose 10 consecutive trades — an unlikely but entirely possible streak — you''ve only lost about 18.3% of your account, not 20%, because each loss compounds on the remaining (shrinking) capital. From 81.7% of your account, recovery is realistic. This is the difference between a bad month and a blown account.</p>
      <div class="highlight-box">A trader risking 10% per trade who hits five consecutive losses has lost 41% of their account and now needs a 70% return just to break even. The 2% trader in the same scenario has lost under 10% — and needs roughly an 11% return to recover. Same losing streak, completely different outcome.</div>
      <h3>How to Calculate Position Size</h3>
      <p>Position Size = (Account Size × Risk %) ÷ (Entry Price − Stop Loss Price). If your account is ₹5,00,000 and you risk 2%, that''s ₹10,000 of risk capital. If your entry is ₹500 and your stop is ₹490, your risk per share is ₹10. Position size = ₹10,000 ÷ ₹10 = 1,000 shares. Every trade, every time — no exceptions, no "just this once."</p>
      <h3>Why Traders Ignore It Anyway</h3>
      <p>FOMO. When a setup "feels" perfect, traders double or triple their normal size — and this is exactly the moment the market tends to punish hardest, because conviction and position sizing should never be correlated. The CFA Risk Framework removes the emotional decision entirely: position size is calculated mechanically before entry, and it never changes based on how confident you feel.</p>
      <p style="color:rgba(255,224,102,0.9);font-style:italic;margin-top:1.5rem;">We cover position sizing in granular detail in the Edge + Precision Bundle. Book a Discovery Call to find the right course for your level.</p>
    ', 'Risk Management', 'risk-management', 'free', '2026-05-27', 'shield', '#22c55e', 'linear-gradient(135deg,#0a2a1a 0%,#0d4a2a 100%)', false, '6 min read');
insert into public.articles (title, excerpt, body, category, cat, access, date, icon, color, bg, featured, readtime) values ('Revenge Trading: The Emotional Trap That Destroys Accounts and How to Escape It', 'Every trader faces losing streaks. The difference between those who survive and those who blow up is entirely psychological.', '
      <p>Every trader, no matter how skilled, faces losing streaks. What separates the traders who survive long enough to become consistently profitable from the ones who blow up their accounts isn''t skill — it''s almost entirely psychological.</p>
      <h3>The Cycle</h3>
      <p>A loss triggers an immediate, almost involuntary urge to "win it back" — right now, in the very next trade. This leads to oversized positions taken without a real setup, entered purely on emotion. When that trade also loses (which it usually does, because it was never a real trade to begin with), the cycle accelerates: bigger size, less planning, faster decisions, more losses.</p>
      <div class="highlight-box">Kahneman and Tversky''s research on loss aversion shows the pain of a loss is felt roughly 2.5x more intensely than the pleasure of an equivalent gain. This asymmetry is precisely what drives revenge trading — your brain isn''t malfunctioning, it''s doing exactly what evolution built it to do. It just happens to be terrible for trading.</p>
      <h3>Recognising It in Real Time</h3>
      <p>The tells are consistent: trading size that doesn''t match your plan, entering without a clear invalidation level, a racing pulse, the thought "I just need this one to work." If you notice even one of these after a loss, you are no longer trading a strategy — you''re trading an emotion.</p>
      <h3>Breaking the Cycle</h3>
      <p>The CFA Framework enforces a mandatory cool-down after any loss exceeding your daily risk limit — no exceptions, no "I''ll just watch the screen." Concretely: define your maximum daily loss before the session starts (e.g. 4% of capital), and if you hit it, you are done trading for the day, full stop. This single rule, enforced without negotiation, prevents the vast majority of catastrophic single-day losses we see in retail accounts.</p>
      <h3>Building Your Own Circuit Breaker</h3>
      <p>Write your daily loss limit down before the market opens. Tell a trading partner or mentor what it is. The goal isn''t to eliminate emotion — that''s impossible — it''s to build a system that takes the decision out of your hands at the exact moment you''re least equipped to make it well.</p>
      <p style="color:rgba(255,224,102,0.9);font-style:italic;margin-top:1.5rem;">Our Trading Psychology module walks through the full daily routine professional traders use to manage this. Book a Discovery Call to learn more.</p>
    ', 'Psychology', 'psychology', 'free', '2026-05-20', 'psychology', '#e879f9', 'linear-gradient(135deg,#2a0f18 0%,#4a1c30 100%)', false, '7 min read');
insert into public.articles (title, excerpt, body, category, cat, access, date, icon, color, bg, featured, readtime) values ('Call vs. Put: A Beginner''s Guide to Options Without the Confusion', 'Options intimidate most beginners because they are taught wrong. This strips away the jargon and gives you a practical mental model.', '
      <p>Options intimidate most beginners because they are taught backwards — starting with Greeks and payoff diagrams before anyone explains the simple idea underneath all of it. Let''s fix that.</p>
      <h3>The Simple Version</h3>
      <p>A <strong>Call option</strong> gives you the right (not the obligation) to buy an asset at a fixed price — the strike price — before a set expiry date. You buy a Call when you expect the price to go up. A <strong>Put option</strong> gives you the right to sell at a fixed price — you buy a Put when you expect the price to go down.</p>
      <p>That''s genuinely the whole concept. Everything else — Delta, Theta, Vega, implied volatility — describes <em>how the price of that right changes</em>, not what the right itself means.</p>
      <h3>Why Options Cost Money: Premium</h3>
      <p>The price you pay for an option is called the premium, and it has two components: intrinsic value (how far "in the money" the option already is) and time value (how much time remains for the bet to play out, plus how volatile the market currently is). This is why two options on the same stock at different expiries cost different amounts even with an identical strike price.</p>
      <h3>Premium Decay — The Silent Killer</h3>
      <p>Time is always working against option buyers. Every single day that passes, an option loses a little value purely from time passing — even if the underlying price doesn''t move at all. This is called Theta decay, and it accelerates sharply in the final week before expiry. This is the single biggest reason most retail option <em>buyers</em> lose money over time, even when they''re directionally right — they''re often right too slowly.</p>
      <div class="highlight-box">A useful beginner mental model: buying options is like buying a lottery ticket with a built-in countdown timer. Being directionally correct isn''t enough — you need to be correct within the time the option gives you, by enough magnitude to overcome the premium you paid.</div>
      <h3>Where Most Beginners Go Wrong</h3>
      <p>New traders buy far out-of-the-money options because they''re cheap, not because they make statistical sense. A ₹5 option "feels" like a small bet, but it usually has a very low probability of ever becoming profitable before expiry. Understanding strike selection relative to your actual market view — not your account size — is the first real skill in options trading.</p>
      <p style="color:rgba(255,224,102,0.9);font-style:italic;margin-top:1.5rem;">We build the complete options foundation — strike selection, premium behaviour, and the Greeks — inside the Edge + Precision Bundle.</p>
    ', 'F&O Basics', 'fo-basics', 'free', '2026-05-13', 'description', '#38bdf8', 'linear-gradient(135deg,#0a1a2e 0%,#102a50 100%)', false, '6 min read');
insert into public.articles (title, excerpt, body, category, cat, access, date, icon, color, bg, featured, readtime) values ('CFA Option Premium Charts: Reading Volatility Before It Explodes', 'This deep-dive covers the exact option premium chart setups we use to identify volatility expansion before it happens. Includes annotated real trade examples from live market sessions over the past quarter, with entry, target, and stop-loss marked on each chart.', '
      <h3>Why Premium Charts, Not Just Price Charts</h3>
      <p>Most traders only ever look at the price chart of the underlying. Professional option sellers also chart the <em>premium itself</em> — because premium behaves differently from price, especially around implied volatility (IV) expansion and contraction. Reading these patterns early is how we position ahead of major moves rather than reacting after they happen.</p>
      <h3>The Pre-Expansion Signature</h3>
      <p>Before a volatility expansion, premium on at-the-money options typically compresses into an unusually tight range relative to its own 20-session average — even while the underlying appears to be moving normally. This compression is the option market quietly pricing in complacency, and it is one of the most reliable early-warning signs we track.</p>
      <h3>Trade Setup: The Compression Break</h3>
      <p><strong>Trigger:</strong> ATM premium compresses to &lt;60% of its 20-session average for 3+ consecutive sessions, then closes above the upper compression band on rising volume.<br/>
      <strong>Entry:</strong> Long straddle or strangle, sized to 1.5% portfolio risk.<br/>
      <strong>Stop-Loss:</strong> Time-based — exit if no expansion within 4 sessions.<br/>
      <strong>Target:</strong> Scale out as IV rank crosses above 65, fully exit above 80.</p>
      <h3>Real Trade Example — BANKNIFTY, April 2026</h3>
      <p>ATM straddle premium compressed to 54% of its average for 4 sessions heading into an RBI policy week. We entered the straddle on the breakout session at a combined premium of ₹612. IV rank expanded from 38 to 71 within 3 sessions as the policy surprised markets, and the position was scaled out in two tranches for a combined 64% gain on premium.</p>
      <h3>Risk Notes</h3>
      <p>This strategy has a defined, time-boxed risk (the premium paid) but a non-trivial base rate of false signals — expect roughly 4 in 10 setups to expire near worthless. Sizing discipline matters more here than in almost any other strategy we teach, precisely because the win rate is lower even though the payoff skew is favourable.</p>
    ', 'Options Strategy', 'options-strategy', 'premium', '2026-05-06', 'auto_graph', '#FFD24D', 'linear-gradient(135deg,#2e2208 0%,#56400a 100%)', false, '10 min read');
insert into public.articles (title, excerpt, body, category, cat, access, date, icon, color, bg, featured, readtime) values ('Building a Target-Based Equity Portfolio: Sector Rotation & Stock Selection', 'A comprehensive walkthrough of the CFA Academy target-based investing framework. Covers sector rotation signals, stock screening criteria, position sizing across a multi-stock portfolio, and capital allocation rules.', '
      <h3>Sector Rotation: The Macro Layer</h3>
      <p>Capital flows between sectors in fairly predictable cycles tied to interest rate direction, earnings momentum, and the broader economic cycle. Before screening individual stocks, the CFA Academy framework starts by identifying which 2–3 sectors are receiving net institutional inflows — buying the right stock in the wrong sector is fighting the tide.</p>
      <h3>The Stock Screening Criteria</h3>
      <p>Within a favoured sector, we screen for: relative strength versus the sector index over the past 3 months, earnings growth acceleration (not just positive growth — accelerating growth), and a clean technical structure with no major overhead supply zones within 15% of current price. Stocks that pass all three move to the watchlist; very few do, by design.</p>
      <div class="highlight-box">A common mistake: buying a fundamentally "cheap" stock in a sector receiving net institutional outflows. Cheap stocks in unloved sectors can stay cheap for years — value without a catalyst is not a thesis, it''s a hope.</div>
      <h3>Position Sizing Across a Multi-Stock Portfolio</h3>
      <p>No single position should exceed 8–10% of total portfolio value at cost, and no single sector should exceed 30%, regardless of conviction. This isn''t a lack of confidence — it''s an acknowledgment that even well-researched theses are wrong often enough that concentration risk has to be managed structurally, not just intellectually.</p>
      <h3>Capital Allocation Rules</h3>
      <p>We allocate in tranches — an initial 50% position on the original thesis, with the remaining 50% added only if the thesis is confirmed by subsequent price action and at least one earnings cycle. This avoids the common error of being "all in" on day one of a multi-month thesis.</p>
      <h3>Rebalancing Discipline</h3>
      <p>Portfolios are reviewed monthly, not daily. Positions that breach the sector rotation signal (the sector falls out of favour for two consecutive months) are trimmed regardless of the individual stock''s chart — because the macro tailwind that justified the position in the first place is no longer there.</p>
      <p style="color:rgba(255,224,102,0.9);font-style:italic;margin-top:1.5rem;">This is the complete framework taught in The CFA Academy Framework for Stock Investing — join the waitlist from the Courses section.</p>
    ', 'Portfolio Building', 'portfolio', 'premium', '2026-04-29', 'trending_up', '#fbbf24', 'linear-gradient(135deg,#261c06 0%,#46320c 100%)', false, '11 min read');
insert into public.articles (title, excerpt, body, category, cat, access, date, icon, color, bg, featured, readtime) values ('The Trader''s Guide to Doing Everything Wrong First & 6 Steps to Recover', 'The market does not care about your predictions. The sooner a trader accepts this, the sooner he can stop trying to predict the market and start learning how to work with it.', '
      <p>Let''s begin with some bad news. The market does not care about your predictions. It does not know your target, it does not respect your confidence, or feel sorry for your stop loss. The sooner a trader accepts this reality, the sooner he can stop trying to predict the market and start learning how to work with it.</p>
      <p>Successful intraday trading is surprisingly boring. No secret indicators. No magic candles. No WhatsApp groups with "sure-shot calls." No uncle whose friend''s neighbour made ₹50,000 in a day. Instead, it is a structured process followed repeatedly with discipline and consistency. Let''s see how.</p>
      <h3>1. Have a Time-Tested Trading Setup</h3>
      <p>Most traders start with a setup they found on YouTube at 2 AM. The thumbnail promised: "95% Accuracy | Nifty Jackpot | Watch Before It Gets Deleted." Three days later, the account is deleted instead.</p>
      <p>A profitable trader needs a setup that has been tested across different market conditions — trending markets, sideways markets, volatile markets, and days when the market seems personally offended by your existence. Borrow a setup or build a setup, but you should have a working setup.</p>
      <h3>2. Build Conviction Through Backtesting</h3>
      <p>Most traders trust a strategy after one winning trade. Professional traders trust a strategy after hundreds of trades. There is a slight difference. Backtesting tells you how often it wins, how often it loses, what drawdowns to expect, and whether you should trust it or quietly uninstall it.</p>
      <div class="highlight-box">Confidence can come from profits later, but it should come from your backtest data now.</div>
      <h3>3. Wait for Your Setup and Follow Your Plan</h3>
      <p>This is where trading becomes difficult — not because the market is complicated, but because human beings are. The market may offer 100 opportunities in a day. Unfortunately, your setup may only appear once. The average trader takes 7 random trades, misses the actual setup, then complains that the strategy doesn''t work.</p>
      <p>A successful trader learns a valuable skill: doing absolutely nothing until the setup appears. Patience in trading feels unproductive. Ironically, it is often the most productive thing you can do.</p>
      <h3>4. Maintain Risk-Reward Discipline</h3>
      <p>Every trader loves targets. Very few love stop losses. Unfortunately, the market requires both. Even the best setup will fail occasionally — the difference between successful and unsuccessful traders is not the number of winning trades, it is how they handle losing trades.</p>
      <p>A good trader asks: How much am I risking? What is my potential reward? Is this trade worth taking? A bad trader asks: "Bhai, target kya hai?" One trader survives. The other becomes content for social media.</p>
      <h3>5. Develop Trading Psychology</h3>
      <p>At some point, every trader discovers that the biggest problem is not the market. It is the person staring back from the screen. Fear. Greed. FOMO. Revenge trading. Overconfidence. These emotions can destroy months of progress in a single afternoon.</p>
      <p>Trading psychology is learning when to hold, when to exit, when to stay out, and most importantly, when to stop looking at someone else''s P&amp;L screenshots. The market rewards discipline far more than intelligence.</p>
      <h3>6. Know When to Stop</h3>
      <p>One of the most underrated skills in trading is knowing when the day is over. Your setup appeared. You took the trade. You followed the plan. You booked the profit or accepted the loss. Congratulations. Go outside. Touch grass. Call it a day.</p>
      <p>Most traders continue trading because they believe the next trade will make the day better. Usually, it makes the broker richer. Overtrading has destroyed more accounts than bad setups ever have.</p>
      <h3>The Final Truth</h3>
      <p>Most traders spend years searching for the perfect strategy. The irony? The strategy is rarely the problem. The real challenge is trusting the setup, waiting patiently, managing risk, following the plan, and repeating the process every day.</p>
      <div class="highlight-box">Consistency in trading is not built by finding a magical indicator. It is built by doing ordinary things extraordinarily well, day after day, while resisting the constant urge to do something stupid. And if that sounds boring... congratulations. You''re finally starting to understand what successful trading looks like.</div>
      <h3>Why Mentorship Matters</h3>
      <p>Understanding a trading setup is only the beginning. The real challenge lies in implementing it consistently in live market conditions. This is where most beginners struggle — overwhelmed by market noise, conflicting opinions, and emotional decision-making.</p>
      <p>A recorded course can teach concepts. A mentor helps you apply them. Through CFA''s One-on-One Mentorship Program, traders learn how to implement the CFA framework in live markets while understanding the thought process behind every decision: what to focus on during live market hours, how to filter noise and distractions, how to evaluate trade opportunities, when to enter, hold, exit, or stay out, and how to think like a disciplined trader.</p>
      <p style="color:rgba(255,224,102,0.9);font-style:italic;margin-top:1.5rem;">Because successful trading is not just about knowing a setup. It is about knowing how to execute it consistently when real money and real emotions are involved. Book a Discovery Call to learn more.</p>
    ', 'Trading Psychology', 'psychology', 'free', '2026-06-17', 'description', '#22c55e', 'linear-gradient(135deg,#0a2a1a 0%,#0d4a2a 100%)', true, '9 min read');
insert into public.articles (title, excerpt, body, category, cat, access, date, icon, color, bg, featured, readtime) values ('The Trader’s Journey: Indicators, Hope & Heartbreak', 'Almost everyone, at some point, thinks: ‘How difficult can it be? Buy low, sell high.’ The market has a wonderful way of introducing itself.', '
      <p>Trading is a fascinating business. It has the unique ability to attract anybody and everybody on the planet, even people who have never looked at a chart in their lives. Almost everyone, at some point, thinks: "How difficult can it be? Buy low, sell high. Simple." The market, however, has a wonderful way of introducing itself.</p>
      <p>A typical trader begins his journey with complete confidence and absolutely no idea what he is doing. He opens a trading account, watches a few YouTube videos, learns two candle patterns, discovers leverage, and is now convinced that financial freedom is just three trades away.</p>
      <p>Terms like market structure, risk management, patience, discipline, position sizing, and risk-reward ratio belong to a distant galaxy. The only strategy at this stage is hope.</p>
      <h3>Reality Arrives</h3>
      <p>A few weeks later, the trader discovers that the market is strangely unwilling to cooperate with his plans. His account begins to shrink at a speed that would impress even the best fund managers. After several losses, he concludes that the problem is not him — it''s the market, or his strategy. And thus begins the legendary quest for the Holy Grail.</p>
      <p>He spends countless hours searching for "100% accurate strategy," "secret institutional setup," "never-fail indicator," and "Bank Nifty jackpot strategy." Soon he has collected more indicators than there are stocks in the market. His charts start resembling a Christmas tree.</p>
      <p>He tries one strategy on Monday, another on Wednesday, and a completely different one by Friday. If a strategy produces a losing trade, it is immediately declared useless and replaced by a newer, shinier strategy from the internet.</p>
      <h3>The Expert at Everything Except Profit</h3>
      <p>Months pass. The trader becomes an expert at downloading indicators, watching videos, joining Telegram groups, changing chart colours, and taking screenshots — which he also loves sharing with peers who barely understand them, because he himself doesn''t either. Making money, unfortunately, remains optional.</p>
      <p>Eventually, frustration takes over. The account balance is damaged, confidence is lower than the stop loss he forgot to place, and he decides to quit trading "forever." "Forever," in trading language, usually means two to four weeks.</p>
      <div class="highlight-box">Fresh capital arrives. Motivation returns. The trader is back. This time it will be different. It isn''t. The cycle repeats itself, often faster than before.</div>
      <h3>Breaking the Carousel</h3>
      <p>Random trading leads to losses. Losses lead to strategy hunting. Strategy hunting leads to confusion. Confusion leads to overtrading. Overtrading leads to losses. Losses lead to quitting. Quitting leads to a fresh deposit. And around and around the carousel goes — until the trader discovers a few truths that only successful traders understand: consistency does not come from finding a magical strategy. It comes from having a structured approach, understanding market behaviour, managing risk, developing patience, and executing the same proven process repeatedly till boredom.</p>
      <p style="color:rgba(255,224,102,0.9);font-style:italic;margin-top:1.5rem;">The irony is that most traders spend years searching for a secret setup, only to discover that the real secret was never the setup — it was the discipline to follow one.</p>
    ', 'Trader Mindset', 'psychology', 'free', '2026-06-10', 'psychology', '#f472b6', 'linear-gradient(135deg,#2a0f20 0%,#4a1838 100%)', true, '7 min read');
insert into public.articles (title, excerpt, body, category, cat, access, date, icon, color, bg, featured, readtime) values ('Holy Grails, Telegram Groups & Other Expensive Trading Hobbies', 'Contrary to popular belief, making money in the stock market is actually quite difficult. Losing money, however, is a highly accessible skill — here are 10+ ways traders practice it.', '
      <p>Contrary to popular belief, making money in the stock market is actually quite difficult. Losing money, however, is a highly accessible skill. Acquiring this skill takes no time, as it''s prebuilt into the normal human brain.</p>
      <p>In fact, the stock market offers such a wide variety of money-losing opportunities that it deserves recognition as one of the most inclusive industries on the planet. Engineers lose money. Doctors lose money. Businessmen lose money. Students lose money. The market believes in equality.</p>
      <p>Let''s explore some of the most popular and expensive trading hobbies practiced by retail traders worldwide.</p>
      <h3>Hobby #1: Random Trading</h3>
      <p>Every trader begins here. No setup. No plan. No analysis. Just vibes. "Mujhe lag raha hai upar jayega, sure-shot." This single sentence has probably destroyed more trading accounts than all bear markets combined. The trade is entered. The market immediately falls. The trader develops a second opinion: "Mujhe lag raha hai neeche jayega." Unfortunately, both opinions are usually wrong.</p>
      <h3>Hobby #2: The Holy Grail Hunt</h3>
      <p>After losing money randomly, the trader reaches a powerful conclusion: "The problem is not me. The problem is my strategy." Thus begins the search for the Holy Grail — videos titled "99% Accuracy Strategy," "Secret Institutional Setup," "Bank Nifty Jackpot Formula." By month''s end he has acquired 17 indicators, 9 strategies, 4 courses, and 0 consistency. His chart now resembles a NASA control panel.</p>
      <h3>Hobby #3: Telegram Group Collection</h3>
      <p>At some point every trader joins a Telegram group. Then another. Soon he''s in "Bank Nifty Kings," "Option Millionaires," "Sure Shot Intraday Calls," and "Premium Diamond Elite VIP Group" — half of which are copying signals from the other half. He now receives 15 buy calls, 12 sell calls, 7 breakout alerts, and 4 urgent messages, all at once. Market confusion reaches professional levels.</p>
      <h3>Hobby #4: Chart Decoration</h3>
      <p>Some traders analyze charts. Others decorate them — trend lines, channels, support, resistance, moving averages, VWAP, Supertrend, pivot points, Fibonacci, Gann, Elliott Wave, astrology. Eventually the actual candles become invisible. The chart looks less like a trading screen and more like a civil engineering project.</p>
      <h3>Hobby #5: Strategy Hopping</h3>
      <p>The average retail trader gives a strategy approximately 2.5 losing trades before declaring it useless. Monday: Price Action. Wednesday: SMC. Friday: ICT. Next Monday: Option Selling. One month later: "Nothing works in the market." The strategy never got a chance — the trader changed systems more often than mobile wallpapers.</p>
      <h3>Hobby #6: Averaging Down</h3>
      <p>This hobby deserves special recognition. The market moves against the trader. A logical person would exit. The trader buys more. The market falls again. He buys even more, then proudly announces: "My average price is much better." The market disagrees and keeps falling. He discovers that averaging is not a strategy — it''s simply a faster way to quit trading and become a long-term investor.</p>
      <h3>Hobby #7: Revenge Trading</h3>
      <p>The trader takes a loss. This is acceptable. Then he takes it personally. Now it is war. He doubles position size, removes the stop loss, ignores risk management, forgets every rule. Three hours later the market has won the war and captured additional capital, often more than 20x his daily risk limit.</p>
      <h3>Hobby #8: Overtrading</h3>
      <p>The market opens at 9:15. The trader takes a trade. Then another. Then a "small recovery trade." Then a "high conviction trade." Then a "last trade." Then a "real last trade." Then a "final final trade." By 3:30 PM he has executed more trades than some professionals take in a month. Broker happy. Trader exhausted.</p>
      <h3>Hobby #9: Unrealistic Expectations</h3>
      <p>The trader starts with ₹20,000. His goal: ₹5 crore in 18 months. Anything less is disappointing. Every trade must be life-changing. Every week must be profitable. Reality eventually arrives carrying a very large stick.</p>
      <h3>Hobby #10: Ignoring Risk-Reward</h3>
      <p>Many traders spend hours finding entries and approximately 4 seconds planning exits. Entry: highly researched. Stop loss: "let''s see." Target: "moon." This generally produces predictable outcomes.</p>
      <div class="highlight-box">The most expensive hobby of all isn''t random trading, Telegram groups, overtrading, or even revenge trading. It''s believing that consistency can be achieved without process. Most traders spend years searching for better indicators, better strategies, better calls, better groups. Very few spend time developing patience, discipline, risk management, market understanding, and consistent execution. Ironically, those are the things that actually matter.</div>
      <h3>Final Thoughts</h3>
      <p>The market offers more than 10,000 ways to lose money. Fortunately, making money requires far fewer things: one proven setup, one structured process, one risk management framework, one disciplined mindset, and enough patience to avoid every "sure-shot" opportunity that appears on Telegram.</p>
      <p style="color:rgba(255,224,102,0.9);font-style:italic;margin-top:1.5rem;">Because in trading, the goal is not to find the Holy Grail. The goal is to stop behaving like you''re searching for one.</p>
    ', 'Risk Management', 'risk-management', 'free', '2026-06-03', 'auto_graph', '#facc15', 'linear-gradient(135deg,#2a1f08 0%,#4a3510 100%)', true, '11 min read');

-- backtests
insert into public.backtests (title, excerpt, body, instrument, timeframe, result, access, date, icon, color, bg, readtime) values ('NIFTY 50 — Breakout Retest at 24,650 Support', 'A clean breakout-and-retest setup on the 15-min chart, with entry triggered on the retest candle and a 1:2.4 risk-reward outcome.', '
      <p><strong>Setup:</strong> NIFTY broke above the 24,650 resistance zone on rising volume, then pulled back to retest the level as support before continuing higher.</p>
      <p><strong>Entry:</strong> 24,668 on the retest confirmation candle &nbsp;|&nbsp; <strong>Stop-Loss:</strong> 24,590 &nbsp;|&nbsp; <strong>Target:</strong> 24,855</p>
      <p><strong>Result:</strong> Target hit within 2 hours. Risk-reward achieved: 1:2.4.</p>
      <p style="color:rgba(255,224,102,0.9);font-style:italic;margin-top:1.5rem;">Logged here as part of our daily backtesting log — not investment advice, for educational reference only.</p>
    ', 'NIFTY 50', '15 min', 'Win', 'free', '2026-06-22', 'candlestick_chart', '#F4C20D', 'linear-gradient(135deg,#2a2008 0%,#4a3508 100%)', '4 min read');
insert into public.backtests (title, excerpt, body, instrument, timeframe, result, access, date, icon, color, bg, readtime) values ('BANK NIFTY — Failed Range Breakout, Stop Honoured', 'A range breakout that reversed quickly. A reminder that even valid setups fail — the value is in the process, not any single trade.', '
      <p><strong>Setup:</strong> BANK NIFTY attempted to break above a 3-day consolidation range on the 5-min chart.</p>
      <p><strong>Entry:</strong> 52,410 &nbsp;|&nbsp; <strong>Stop-Loss:</strong> 52,310 &nbsp;|&nbsp; <strong>Result:</strong> Stop hit. -1R.</p>
      <p>No change in process despite the loss — the setup met every criterion in the framework going in. This is logged exactly as it happened, including losses, because a backtesting log only has value if it''s honest.</p>
    ', 'BANK NIFTY', '5 min', 'Loss', 'free', '2026-06-21', 'shield', '#22c55e', 'linear-gradient(135deg,#0a2a1a 0%,#0d4a2a 100%)', '3 min read');
insert into public.backtests (title, excerpt, body, instrument, timeframe, result, access, date, icon, color, bg, readtime) values ('RELIANCE — Daily Chart Higher-Low Continuation', 'A textbook higher-low entry within an established uptrend, taken on the daily chart with a multi-day target.', '
      <p><strong>Setup:</strong> RELIANCE formed a clean higher-low on the daily chart after a 5% pullback within an existing uptrend.</p>
      <p><strong>Entry:</strong> ₹2,945 &nbsp;|&nbsp; <strong>Stop-Loss:</strong> ₹2,890 &nbsp;|&nbsp; <strong>Target:</strong> ₹3,060</p>
      <p><strong>Result:</strong> Target hit on day 4. Risk-reward achieved: 1:2.1.</p>
    ', 'RELIANCE', 'Daily', 'Win', 'free', '2026-06-19', 'trending_up', '#fbbf24', 'linear-gradient(135deg,#261c06 0%,#46320c 100%)', '4 min read');
insert into public.backtests (title, excerpt, body, instrument, timeframe, result, access, date, icon, color, bg, readtime) values ('NIFTY 50 — Hourly Trendline Bounce Into Resistance', 'An older archived setup — now beyond the 30-day free window. Unlock with any course purchase to view the full breakdown.', '
      <p><strong>Setup:</strong> NIFTY respected a rising hourly trendline for the third consecutive touch, with confluence from the 50-period EMA.</p>
      <p><strong>Entry:</strong> 23,980 &nbsp;|&nbsp; <strong>Stop-Loss:</strong> 23,905 &nbsp;|&nbsp; <strong>Target:</strong> 24,150</p>
      <p><strong>Result:</strong> Target hit. Risk-reward achieved: 1:2.3.</p>
    ', 'NIFTY 50', '1 hour', 'Win', 'free', '2026-05-09', 'auto_graph', '#38bdf8', 'linear-gradient(135deg,#0a1a2e 0%,#102a50 100%)', '4 min read');
